#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "master" ]; then
	echo "husky: run lint-staged"
    npm run lint
    echo "husky: run tests"
    npm run cy:run
fi